// ─── Message & Citation Types ──────────────────────────────────────────────

export type MessageRole = 'user' | 'assistant' | 'system';

export interface Citation {
  id: string;
  index: number;           // [1], [2] etc shown inline
  sourceId: string;
  sourceTitle: string;
  excerpt: string;
  page?: number;
  chunkId?: string;
}

export interface EvidenceSection {
  id: string;
  title: string;
  content: string;
  citations: Citation[];
  collapsed: boolean;
}

export interface MessageAttachment {
  id: string;
  name: string;
  type: SupportedFileType;
  size: number;
  url?: string;             // blob URL or remote URL
  status: 'uploading' | 'processing' | 'ready' | 'error';
  error?: string;
}

export interface Message {
  id: string;
  role: MessageRole;
  content: string;
  timestamp: Date;
  attachments?: MessageAttachment[];
  citations?: Citation[];
  evidence?: EvidenceSection[];
  isStreaming?: boolean;
  error?: string;
}

// ─── Session / Conversation ────────────────────────────────────────────────

export interface Session {
  id: string;
  title: string;
  createdAt: Date;
  updatedAt: Date;
  messages: Message[];
  pinnedSources: UploadedFile[];
  messageCount: number;
  preview?: string;         // last message snippet
}

// ─── File Upload ───────────────────────────────────────────────────────────

export type SupportedFileType =
  | 'pdf'
  | 'docx'
  | 'md'
  | 'txt'
  | 'png'
  | 'jpg'
  | 'jpeg'
  | 'webp'
  | 'gif';

/** Maps to backend Document.status column */
export type DocumentStatus =
  | 'uploaded'   // just stored in MinIO, DB row created
  | 'parsing'    // Celery parse_document task running
  | 'parsed'     // Module 2 done — preview available
  | 'indexing'   // Celery embed_document task running
  | 'indexed'    // fully in Qdrant — ready for RAG
  | 'error';

/** Frontend display status (maps multiple backend states to fewer UI states) */
export type FileDisplayStatus = 'uploading' | 'processing' | 'ready' | 'error';

export interface UploadedFile {
  id: string;               // local UUID generated by frontend
  docId?: string;           // server-assigned doc_id from POST /api/v1/upload
  name: string;
  type: SupportedFileType;
  size: number;             // bytes
  uploadedAt: Date;
  status: FileDisplayStatus;
  backendStatus?: DocumentStatus; // raw status from polling
  progress?: number;        // 0-100 (upload phase only)
  error?: string;
  chunkCount?: number;
  url?: string;
  previewUrl?: string;
}

// ─── API Response Shapes ──────────────────────────────────────────────────

/** Response from POST /api/v1/upload */
export interface DocumentUploadResponse {
  doc_id: string;
  filename: string;
  s3_key: string;
  status: DocumentStatus;
  created_at: string;
}

/** Response from GET /api/v1/documents/{id} */
export interface DocumentRecord {
  doc_id: string;
  filename: string;
  content_type: string;
  size: number;
  status: DocumentStatus;
  created_at: string;
  s3_key: string;
}

/** Response from GET /api/v1/documents/{id}/preview */
export interface PreviewData {
  doc_id: string;
  preview_type: 'pdf' | 'text' | 'image' | 'markdown';
  content?: string;    // plain text / markdown content
  url?: string;        // presigned S3 URL for PDF / image
  page_count?: number;
}

// ─── File Validation ──────────────────────────────────────────────────────

export interface FileValidationError {
  file: string;               // filename
  reason: 'size' | 'type' | 'mime_mismatch';
  message: string;
}

// ─── WebSocket / API ───────────────────────────────────────────────────────

export type WSMessageType =
  | 'chat_start'
  | 'chat_token'
  | 'chat_citation'
  | 'chat_done'
  | 'chat_error'
  | 'chat_version_ready'
  | 'file_progress'
  | 'file_ready'
  | 'file_error'
  | 'ping'
  | 'pong';

export interface WSMessage {
  type: WSMessageType;
  payload: unknown;
}

export interface ChatStartPayload {
  messageId: string;
  sessionId: string;
}

export interface ChatTokenPayload {
  messageId: string;
  token: string;
}

export interface ChatCitationPayload {
  messageId: string;
  citation: Citation;
}

export interface ChatDonePayload {
  messageId: string;
  usage?: { promptTokens: number; completionTokens: number };
}

export interface ChatErrorPayload {
  messageId: string;
  error: string;
}

export interface FileProgressPayload {
  fileId: string;
  progress: number;
  stage: 'uploading' | 'chunking' | 'embedding' | 'indexing';
}

// ─── Export ────────────────────────────────────────────────────────────────

export type ExportFormat = 'pdf' | 'docx' | 'md' | 'json';

export interface ExportOptions {
  doc_id: string;
  version_id?: number;
  export_format: ExportFormat;
}

export interface ExportResponse {
  job_id: number;
  status: 'processing' | 'completed' | 'failed';
  format: string;
  download_url: string;
  edits_applied: number;
  message: string;
}

// ─── UI State ──────────────────────────────────────────────────────────────

export interface AppSettings {
  theme: 'light' | 'dark' | 'system';
  streamingEnabled: boolean;
  citationsVisible: boolean;
  compactMode: boolean;
  wsUrl: string;
  apiBaseUrl: string;
}

export interface PanelState {
  sidebarOpen: boolean;
  rightPanelOpen: boolean;
  rightPanelTab: 'files' | 'preview' | 'export' | 'settings';
}

// ─── Backend RAG / Edit types ─────────────────────────────────────────────

/**
 * One parsed block from GET /api/v1/chunks/{doc_id}
 * Matches backend ParsedContent model exactly.
 */
export interface ParsedContent {
  doc_id: string;
  chunk_index: number;   // deterministic ordering key
  page_no: number;
  block_index: number;
  text: string;
  font?: string;
  font_size?: number;
  bbox?: [number, number, number, number]; // [x, y, width, height] in PDF pts
}

/**
 * One edit from GET /api/v1/diff/{version_id}
 * chunk_index is the join key — never use string matching.
 */
export interface EditDiff {
  chunk_index: number;
  page_no: number;
  original_text: string;
  updated_text: string;
  reason: string;
}

/** One row in GET /api/v1/versions/{doc_id} */
export interface DocumentVersion {
  version_id: string;
  version_number: number;
  prompt: string;
  created_at: string;
}

// ─── Layout engine types (src/lib/pretext/layout.ts) ─────────────────────

/** Options for the deterministic text layout engine. */
export interface LayoutOptions {
  /**
   * Container pixel width.  Measured once with ResizeObserver — never causes reflow.
   */
  containerWidth: number;
  fontSize: number;   // px
  fontFamily: string; // e.g. "JetBrains Mono" | "Plus Jakarta Sans"
  lineHeight: number; // px — used for height pre-computation
  /** If true, all chars are assumed the same width (faster — correct for monospace). */
  monospace?: boolean;
}

/**
 * One layout line produced by computeLayout().
 * start/end are absolute character offsets into the fullText string.
 */
export interface LayoutLine {
  text: string;
  start: number;  // inclusive char offset in fullText
  end: number;    // exclusive char offset in fullText
  lineIndex: number;
}

// ─── Text map types (src/lib/text/buildTextMap.ts) ────────────────────────

/**
 * Maps a chunk_index to its character-offset range in the fullText string.
 * Built by buildTextMap() — used as the lookup table for edit mapping.
 */
export interface ChunkMapEntry {
  chunk_index: number;
  start: number; // inclusive
  end: number;   // exclusive
}

export interface TextMap {
  fullText: string;
  chunkMap: ChunkMapEntry[];
}

// ─── Diff / highlight types (src/lib/diff/) ───────────────────────────────

/** A character-range highlight produced by mapEditsToRanges(). */
export interface HighlightRange {
  start: number; // absolute char offset in fullText
  end: number;   // absolute char offset in fullText
  type: 'added' | 'removed' | 'modified';
  reason?: string;
  chunk_index: number; // retained for tooltip / side-by-side display
}

/** A text segment produced by applyHighlights() — ready for rendering. */
export interface HighlightSegment {
  text: string;
  type?: 'added' | 'removed' | 'modified'; // undefined = plain text
  reason?: string;
}
